apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  
  labels:
    app: fastapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      type: redis-pod
      app: fastapi-app
  template:
    metadata:
      name: redis-pod
      labels:
        type: redis-pod
        app: fastapi-app
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379