apiVersion: v1
kind: Service
metadata:
  name: redis
  
  labels:
    type: redis-service
    app: fastapi-app
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    type: redis
    app: fastapi-app