apiVersion: v1
kind: Service
metadata:
  name: celery-flower
  
  labels:
    type: celery-flower-service
    app: fastapi-app
spec:
  type: NodePort
  ports:
    - port: 5555
      targetPort: 5555
  selector:
    type: celery-flower
    app: fastapi-app