apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: local
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      type: redis
      app: redis
  template:
    metadata:
      name: redis
      labels:
        type: redis
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379