apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: local
  labels:
    type: redis
    app: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    type: redis
    app: redis