apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-flower
  namespace: local
  labels:
    app: celery-flower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-flower
  template:
    metadata:
      name: celery-flower
      labels:
        app: celery-flower
    spec:
      containers:
        - name: celery-flower
          image: mher/flower
          envFrom:
          - configMapRef:
              name: redis-settings
          ports:
            - containerPort: 5555
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"