apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: local
  labels:
    app: fastapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      type: api
      app: fastapi-app
  template:
    metadata:
      name: fastapi-app
      labels:
        type: api
        app: fastapi-app
    spec:
      containers:
        - name: fastapi-app-demo
          image: 10.5.0.2:5000/fastapi-celery-playground-fastapi:latest
          imagePullPolicy: Always
          env:
            - name: CELERY_BROKER_URL
              value: "$(CELERY_BROKER_URL)"
            - name: CELERY_BACKEND_URL
              value: "$(CELERY_BACKEND_URL)"
          ports:
            - containerPort: 80


