apiVersion: v1
kind: Service
metadata:
  name: fastapi-app
  namespace: local
  labels:
    app: fastapi-app
spec:
  type: NodePort
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app: fastapi-app
