apiVersion: v1
kind: Service
metadata:
  name: fastapi-app
  namespace: local
  labels:
    type: fastapi-app
    app: fastapi-app
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    type: api
    app: fastapi-app
