apiVersion: v1
kind: Service
metadata:
  name: fastapi-app
  namespace: development
  labels:
    type: fastapi-app-service
    app: fastapi-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    type: api
    app: fastapi-app-demo
