# Rename me as secrets.yaml and populate my values
apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: local
type: Opaque
stringData :
  CELERY_BROKER_URL: redis://redis:6379/0
  CELERY_BACKEND_URL: redis://redis:6379/0