apiVersion: v1
kind: Service
metadata:
  name: celery-flower-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: celery-flower-{{ .Release.Name }}
spec:
  type: NodePort
  ports:
    - name: http
      port: 5555
      targetPort: 5555
  selector:
    app: celery-flower