apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-flower
  namespace: local
  labels:
    app: celery-flower
spec:
  replicas: 1
  selector:
    matchLabels:
      type: celery-flower
      app: celery-flower
  template:
    metadata:
      name: celery-flower
      labels:
        type: celery-flower
        app: celery-flower
    spec:
      containers:
        - name: celery-flower
          image: mher/flower
          env:
            - name: CELERY_BROKER_URL
              value: redis://redis:6379/0
            - name: CELERY_BACKEND_URL
              value: redis://redis:6379/0
          ports:
            - containerPort: 5555