apiVersion: v1
kind: Service
metadata:
  name: celery-flower
  namespace: local
  labels:
    type: celery-flower
    app: celery-flower
spec:
  type: NodePort
  ports:
    - port: 5555
      targetPort: 5555
  selector:
    type: celery-flower
    app: celery-flower