apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
  namespace: local
  labels:
    app: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      name: celery
      labels:
        app: celery
    spec:
      containers:
        - name: celery
          image: krishnasismandal/fastapi-celery-playground-celery_worker:latest
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: redis-settings
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
