apiVersion: v1
kind: Service
metadata:
  name: fastapi-app-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: fastapi-app-{{ .Release.Name }}
spec:
  type: NodePort
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app: fastapi-app
